name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install dependencies
        run: npm install

      - name: Build and export the app
        run: npm run generate

      - name: Install Git LFS
        run: |
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Track files with Git LFS
        run: git lfs track "dist/**/*.+(png|jpg|jpeg|gif|mp4|webm|ogg|mp3|wav|flac|aac|pdf)"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
